### ISSUE TITLE
Helve Hammer doesn't work on some Linux

### ISSUE THREAD

**Issue by XxNinMario64xX** [DArkHekRoMaNT/HelveHammerExtensions#8]
### Mod Version

1.6.0

### CommonLib Version

2.3.7

### Game Version

1.19.8

### OS

Linux

### Play mode

Multiplayer

### Problem

The helve hammer continues to break parts of the unfinished pickaxe head until it completes it, but never outputs the pickaxe head itself. Upon picking up the unfinished pickaxe head while it's complete, it resets to its default, unfinished state as if no work had been done on it. See more in the linked video [here](https://www.youtube.com/watch?v=dL2bc1ixaKg).

### Logs

```bash
Server-Main

3.6.2024 17:11:25 [Notification] Server logger started.
3.6.2024 17:11:25 [Notification] Game Version: v1.19.8 (Stable)
3.6.2024 17:11:25 [Notification] C# Framework: .net 7.0.19
3.6.2024 17:11:25 [Notification] Zstd Version: 1.4.8
3.6.2024 17:11:25 [Notification] Operating System: Linux (Ubuntu 22.04.4 LTS) [Kernel 6.5.0.1023]
3.6.2024 17:11:25 [Event] Launching server...
3.6.2024 17:11:25 [Event] Server v1.19.8, network v1.19.8, api v1.19.0
3.6.2024 17:11:25 [Notification] Entering runphase Initialization
3.6.2024 17:11:25 [Event] Loading configuration...
3.6.2024 17:11:25 [Notification] Entering runphase Configuration
3.6.2024 17:11:26 [Notification] Loading savegame
3.6.2024 17:11:26 [Notification] Loaded existing save game data. Playstyle: surviveandbuild, Playstyle Lang code: surviveandbuild-bands, WorldType: surviveandbuild-bands
3.6.2024 17:11:26 [Notification] Savegame /var/vintagestory/testdata/Saves/default.vcdbs loaded
3.6.2024 17:11:26 [Notification] World size = 1024000 256 1024000
3.6.2024 17:11:26 [Notification] Start discovering assets
3.6.2024 17:11:26 [Notification] Found 1 base assets in category blocktypes
3.6.2024 17:11:26 [Notification] Found 0 base assets in category itemtypes
3.6.2024 17:11:26 [Notification] Found 25 base assets in category lang
3.6.2024 17:11:26 [Notification] Found 0 base assets in category patches
3.6.2024 17:11:26 [Notification] Found 24 base assets in category config
3.6.2024 17:11:26 [Notification] Found 0 base assets in category worldproperties
3.6.2024 17:11:26 [Notification] Found 1 base assets in category sounds
3.6.2024 17:11:26 [Notification] Found 95 base assets in category shapes
3.6.2024 17:11:26 [Notification] Found 21 base assets in category textures
3.6.2024 17:11:26 [Notification] Found 0 base assets in category recipes
3.6.2024 17:11:26 [Notification] Found 0 base assets in category worldgen
3.6.2024 17:11:26 [Notification] Found 3 base assets in category entities
3.6.2024 17:11:26 [Notification] Found 170 base assets in total
3.6.2024 17:11:26 [Event] Building assets...
3.6.2024 17:11:26 [Notification] Entering runphase LoadAssets
3.6.2024 17:11:26 [Notification] Will search the following paths for mods:
3.6.2024 17:11:26 [Notification]     /home/ubuntu/testserver/Mods
3.6.2024 17:11:26 [Notification]     /var/vintagestory/testdata/Mods
3.6.2024 17:11:26 [Notification] Found 5 mods (0 disabled)
3.6.2024 17:11:26 [Notification] Mods, sorted by dependency: game, commonlib, creative, survival, helvehammerext
3.6.2024 17:11:26 [Notification] Instantiated 114 mod systems from 5 enabled mods
3.6.2024 17:11:26 [Notification] [commonlib] Config HelveHammerExtensions.Config, HelveHammerExtensions, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null loaded successfully
3.6.2024 17:11:26 [Notification] External Origins in load order: modorigin@/home/ubuntu/testserver/assets/creative/, modorigin@/home/ubuntu/testserver/assets/survival/, mod@HelveHammerExtensions_VS1.19.0-rc.5_net7_v1.6.0.zip
3.6.2024 17:11:26 [Notification] Found 404 external assets in category blocktypes
3.6.2024 17:11:26 [Notification] Found 242 external assets in category itemtypes
3.6.2024 17:11:26 [Notification] Found 0 external assets in category lang
3.6.2024 17:11:26 [Notification] Found 14 external assets in category patches
3.6.2024 17:11:26 [Notification] Found 56 external assets in category config
3.6.2024 17:11:26 [Notification] Found 25 external assets in category worldproperties
3.6.2024 17:11:26 [Notification] Found 1 external assets in category sounds
3.6.2024 17:11:26 [Notification] Found 3636 external assets in category shapes
3.6.2024 17:11:26 [Notification] Found 23 external assets in category textures
3.6.2024 17:11:26 [Notification] Found 363 external assets in category recipes
3.6.2024 17:11:26 [Notification] Found 478 external assets in category worldgen
3.6.2024 17:11:26 [Notification] Found 64 external assets in category entities
3.6.2024 17:11:26 [Notification] Found 0 external assets in category compatibility
3.6.2024 17:11:26 [Notification] Reloaded lang file with mod assets
3.6.2024 17:11:27 [Error] [helvehammerext] An exception was thrown when trying to start the mod:
3.6.2024 17:11:27 [Error] [helvehammerext] Exception: Patching exception in method virtual Vintagestory.GameContent.EnumHelveWorkableMode Vintagestory.GameContent.ItemWorkItem::GetHelveWorkableMode(Vintagestory.API.Common.ItemStack stack, Vintagestory.GameContent.BlockEntityAnvil beAnvil)
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__10_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.Harmony.PatchAll(Assembly assembly)
   at HarmonyLib.Harmony.PatchAll()
   at HelveHammerExtensions.VanillaPatches.Start(ICoreAPI api)
   at Vintagestory.Common.ModLoader.TryRunModPhase(Mod mod, ModSystem system, ICoreAPI api, ModRunPhase phase) in VintagestoryLib\Common\API\ModLoader.cs:line 629
3.6.2024 17:11:27 [Error] Failed to run mod phase Start for mod HelveHammerExtensions.VanillaPatches
3.6.2024 17:11:27 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
3.6.2024 17:11:27 [Notification] JsonPatch Loader: 27 patches total, successfully applied 38 patches, missing files on 1 patches, no errors
3.6.2024 17:11:29 [Notification] Loaded 3335 unique items
3.6.2024 17:11:33 [Notification] Loaded 9312 unique blocks
3.6.2024 17:11:34 [Notification] Loaded 606 unique entities
3.6.2024 17:11:34 [Notification] BlockLoader: Entities, Blocks and Items loaded
3.6.2024 17:11:34 [Event] Remapping blocks and items...
3.6.2024 17:11:34 [Event] 8 cooking recipes loaded
3.6.2024 17:11:34 [Event] 677 crafting recipes loaded from 233 files
3.6.2024 17:11:34 [Event] 9 metal alloys loaded
3.6.2024 17:11:34 [Event] 241 smithing recipes loaded
3.6.2024 17:11:34 [Event] 55 clay forming recipes loaded
3.6.2024 17:11:34 [Event] 36 knapping recipes loaded
3.6.2024 17:11:34 [Event] 142 barrel recipes loaded
3.6.2024 17:11:34 [Notification] Entering runphase AssetsFinalize
3.6.2024 17:11:35 [Event] Server assets loaded, parsed, registered and finalized
3.6.2024 17:11:35 [Event] Initialising systems...
3.6.2024 17:11:35 [Notification] Entering runphase LoadGamePre
3.6.2024 17:11:35 [Notification] Reloaded 19 weather patterns, 5 wind patterns and 5 weather events
3.6.2024 17:11:35 [Notification] Started 99 systems on Server:
3.6.2024 17:11:35 [Notification]     Mod 'VSEssentials.dll' (game):
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.Core
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.EntityPartitioning
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ErrorReporter
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
3.6.2024 17:11:35 [Notification]         Vintagestory.Essentials.PathfindSystem
3.6.2024 17:11:35 [Notification]         Vintagestory.Essentials.PathFindDebug
3.6.2024 17:11:35 [Notification]         Vintagestory.Essentials.PathfindingAsync
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.JsonExport
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.ModBasicBlocksLoader
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemSyncHarvestableDropsToClient
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemEmotes
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.LeafBlockDecay
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.POIRegistry
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.RoomRegistry
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.WeatherSystemServer
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.WorldMapManager
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.LoadColorMaps
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ClothManager
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GridRecipeLoader
3.6.2024 17:11:35 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenTerra
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenSnowLayer
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenTerraPostProcess
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.DebugSystem
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.UpgradeTasks
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.ChiselBlockBulkSetMaterial
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.NpcControl
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenMaps
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenRockStrataNew
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenHotSprings
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenCreatures
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.WgenCommands
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemExplosionAffectedStability
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.MyceliumSystem
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModsystemButterflySpawnCondsExtra
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemGliding
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ClutterBookshelfUtil
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemResoArchiveCommands
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemAuction
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.Core
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.CharacterSystem
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.DialogueSystem
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.FruitingSystem
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemCommandHandbook
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemTutorial
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemCorpseReturnTeleporter
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemNightVision
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModJournal
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModLootRandomizer
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemRifts
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSleeping
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.TeleporterManager
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModTemperature
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.SystemTemporalStability
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenDungeons
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenDeposits
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.GenStoryStructures
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenCaves
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenStructures
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenBlockLayers
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenPonds
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenVegetationAndPatches
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenRivulets
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenLightSurvival
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.RecipeLoader
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemOreMap
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.ModSystemSnowballs
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.TraderOutfits
3.6.2024 17:11:35 [Notification]         Vintagestory.GameContent.DisableRecipeRegisteringSystem
3.6.2024 17:11:35 [Notification]     Mod 'CommonLib_VS1.19.4_net7_v2.3.7.zip' (commonlib):
3.6.2024 17:11:35 [Notification]         CommonLib.Config.ConfigManager
3.6.2024 17:11:35 [Notification]         CommonLib.Core
3.6.2024 17:11:35 [Notification]     Mod 'VSCreativeMod.dll' (creative):
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.Core
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenBlockLayersFlat
3.6.2024 17:11:35 [Notification]         Vintagestory.ServerMods.GenLightCreative
3.6.2024 17:11:35 [Notification]     Mod 'HelveHammerExtensions_VS1.19.0-rc.5_net7_v1.6.0.zip' (helvehammerext):
3.6.2024 17:11:35 [Notification]         HelveHammerExtensions.Core
3.6.2024 17:11:35 [Notification]         HelveHammerExtensions.VanillaPatches
3.6.2024 17:11:37 [Notification] Server map set
3.6.2024 17:11:37 [Notification] Entering runphase LoadGame
3.6.2024 17:11:37 [Notification] Entering runphase WorldReady
3.6.2024 17:11:37 [Event] Starting world generators...
3.6.2024 17:11:40 [Notification] Reloaded 35 tree generators
3.6.2024 17:11:40 [Event] Loading 7x7x8 spawn chunks...
3.6.2024 17:11:40 [Event] 0% (49 in queue)
3.6.2024 17:11:41 [Event] Begin game ticking...
3.6.2024 17:11:41 [Notification] Entering runphase RunGame
3.6.2024 17:11:41 [Notification] Successfully loaded 0 waypoints
3.6.2024 17:11:41 [Notification] Starting server threads
3.6.2024 17:11:41 [Event] Dedicated Server now running on Port 42422 and all ips!
3.6.2024 17:11:41 [Notification] All clients disconnected, pausing game calendar.
3.6.2024 17:11:50 [Warning] Server overloaded. A tick took 537ms to complete.
3.6.2024 17:12:05 [Notification] A Client attempts connecting via TCP, assigning client id 1
3.6.2024 17:12:05 [Warning] Entity with code game:deer-moose-male-adult has defined a companion spawn game:moose-female-adult, but no such entity type found.
3.6.2024 17:12:05 [Warning] Entity with code game:deer-moose-male-adult has defined a companion spawn game:moose-female-baby, but no such entity type found.
3.6.2024 17:12:05 [Warning] Entity with code game:deer-moose-male-adult has defined a companion spawn game:moose-male-baby, but no such entity type found.
3.6.2024 17:12:06 [Notification] Client uid JQ9K6dh11eXXEOKkwhWunfLi attempting identification. Name: Foxy_Grandpa
3.6.2024 17:12:07 [Notification] Delayed join, need to load one spawn chunk first.
3.6.2024 17:12:07 [Notification] Sending server identification with remap False.  Server control privilege is True
3.6.2024 17:12:07 [Notification] Placing player at 511999.59400878905 138.10898046875 512007.95441191405
3.6.2024 17:12:13 [Event] Foxy_Grandpa [::ffff:73.182.16.130]:28390 joins.
3.6.2024 17:12:13 [Notification] A client reconnected, resuming game calendar.
3.6.2024 17:14:06 [Notification] Handling Command (Foxy_Grandpa) /time set day
3.6.2024 17:16:14 [Notification] Handling Command (Foxy_Grandpa) /stop 
3.6.2024 17:16:14 [Notification] Message to all in group 0: Player Foxy_Grandpa commenced a server shutdown
3.6.2024 17:16:14 [Event] Player Foxy_Grandpa shuts down server.
3.6.2024 17:16:14 [Notification] Last player disconnected, compacting large object heap...
3.6.2024 17:16:15 [Event] Player Foxy_Grandpa got removed. Reason: Server shutting down - Shutdown via server command
3.6.2024 17:16:15 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Shutdown via server command
3.6.2024 17:16:15 [Notification] Server ticking has been suspended
3.6.2024 17:16:15 [Notification] Entering runphase Shutdown
3.6.2024 17:16:15 [Notification] Defragmented listener lists
3.6.2024 17:16:15 [Event] Mods and systems notified, now saving everything...
3.6.2024 17:16:15 [Event] Saved player world data...
3.6.2024 17:16:15 [Event] Saved map regions...
3.6.2024 17:16:15 [Event] Saved map chunks...
3.6.2024 17:16:15 [Event] Saved loaded chunks...
3.6.2024 17:16:15 [Event] Saved generating chunks...
3.6.2024 17:16:15 [Event] Saved savegamedata...2
3.6.2024 17:16:15 [Event] World saved! Saved 152 chunks, 446 mapchunks, 4 mapregions.
3.6.2024 17:16:15 [Event] Shutting down 6 server threads... 
3.6.2024 17:16:15 [Event] Killed console thread
3.6.2024 17:16:16 [Event] All threads gracefully shut down
3.6.2024 17:16:16 [Event] Doing last tick...
3.6.2024 17:16:16 [Event] Stopped the server!
```

### Mods

```bash
CommonLib_VS1.19.4_net7_v2.3.7
HelveHammerExtensions_VS1.19.0-rc.5_net7_v1.6.0
```

**Comment by XxNinMario64xX** [comment]
I'm also running this on a server that I can provide if you wish to see it for yourself. Just DM mention me in the VS server or DM me (DisVern). I can recreate the issue consistently there.

**Comment by DArkHekRoMaNT** [comment]
Have you tried any other mods with harmony patches like XSkills? It seems that Harmony patches don't work correctly on ARM. So this may be unfixable on my side

**Comment by XxNinMario64xX** [comment]
I have tried XSkills on the server and it works fine. The only other two mods I've had trouble with thus far is Rivers and Plains & Valleys, but I could simply patch those directly into the server assets to fix it. I can't do the same with helve hammer extensions. If there was a way to directly add the mod to the server then I'd do it, but even I couldn't do that (tried adding helvehammerworkable to all toolheads in accordance with the patches and it still didn't work. I probably did it wrong.)

**Comment by DArkHekRoMaNT** [comment]
You can't patch those directly. How? This is Harmony game code patch not json

**Comment by DArkHekRoMaNT** [comment]
Anyway, this is a very strange problem. I don't know how XSkills works for you if Harmony even can't apply my simple patch...
